# Generated by Django 2.1.5 on 2019-03-22 08:05

import coffeeshop.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffeeshop_list', models.CharField(choices=[('STARBUCKS', 'Starbucks')], max_length=20)),
                ('name', models.CharField(max_length=100, verbose_name='커피')),
                ('coffee_info', models.TextField(blank=True, verbose_name='커피소개')),
                ('coffee_size', models.CharField(blank=True, max_length=80, verbose_name='커피사이즈')),
                ('calorie', models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='칼로리')),
                ('saturated_fat', models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='포화지방')),
                ('protein', models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='단백질')),
                ('sodium', models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='나트룸')),
                ('sugars', models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='당류')),
                ('caffeine', models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='카페인')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '커피',
                'verbose_name_plural': '커피 목록',
            },
        ),
        migrations.CreateModel(
            name='CoffeeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리 목록',
            },
        ),
        migrations.CreateModel(
            name='CoffeeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ImageField(blank=True, upload_to=coffeeshop.models.coffee_path, verbose_name='커피이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.Coffee', verbose_name='커피')),
            ],
            options={
                'verbose_name': '커피이미지',
                'verbose_name_plural': '커피이미지 목록',
            },
        ),
        migrations.AddField(
            model_name='coffee',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffeeshop.CoffeeCategory', verbose_name='카테고리'),
        ),
    ]
