# Generated by Django 2.1.5 on 2019-03-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='name',
            field=models.CharField(max_length=100, verbose_name='커피'),
        ),
    ]
