# Generated by Django 2.1.5 on 2019-09-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='coffeeshop_list',
            field=models.CharField(choices=[('STARBUCKS', '스타벅스'), ('ATWOSOMEPLACE', '투썸플레이스')], max_length=20),
        ),
    ]
