# Generated by Django 2.1.5 on 2019-04-20 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0002_cronlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CronLog',
        ),
    ]
